2020-01-21 21:22:13.454142: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/ohpc/pub/spack/opt/spack/linux-centos7-x86_64/gcc-8.3.0/python-3.7.4-3tniqr5iaaddvr3mbambcec3e5ta5qjp/lib:/opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/lib:/opt/ohpc/pub/compiler/gcc/8.3.0/lib64:/cm/local/apps/cuda-driver/libs/390.46/lib64
2020-01-21 21:22:13.454142: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/ohpc/pub/spack/opt/spack/linux-centos7-x86_64/gcc-8.3.0/python-3.7.4-3tniqr5iaaddvr3mbambcec3e5ta5qjp/lib:/opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/lib:/opt/ohpc/pub/compiler/gcc/8.3.0/lib64:/cm/local/apps/cuda-driver/libs/390.46/lib64
2020-01-21 21:22:13.455622: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/ohpc/pub/spack/opt/spack/linux-centos7-x86_64/gcc-8.3.0/python-3.7.4-3tniqr5iaaddvr3mbambcec3e5ta5qjp/lib:/opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/lib:/opt/ohpc/pub/compiler/gcc/8.3.0/lib64:/cm/local/apps/cuda-driver/libs/390.46/lib64
2020-01-21 21:22:13.458209: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/ohpc/pub/spack/opt/spack/linux-centos7-x86_64/gcc-8.3.0/python-3.7.4-3tniqr5iaaddvr3mbambcec3e5ta5qjp/lib:/opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/lib:/opt/ohpc/pub/compiler/gcc/8.3.0/lib64:/cm/local/apps/cuda-driver/libs/390.46/lib64
2020-01-21 21:22:13.454944: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/ohpc/pub/spack/opt/spack/linux-centos7-x86_64/gcc-8.3.0/python-3.7.4-3tniqr5iaaddvr3mbambcec3e5ta5qjp/lib:/opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/lib:/opt/ohpc/pub/compiler/gcc/8.3.0/lib64:/cm/local/apps/cuda-driver/libs/390.46/lib64
2020-01-21 21:22:13.454965: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2020-01-21 21:22:13.458168: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/ohpc/pub/spack/opt/spack/linux-centos7-x86_64/gcc-8.3.0/python-3.7.4-3tniqr5iaaddvr3mbambcec3e5ta5qjp/lib:/opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/lib:/opt/ohpc/pub/compiler/gcc/8.3.0/lib64:/cm/local/apps/cuda-driver/libs/390.46/lib64
2020-01-21 21:22:13.458192: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2020-01-21 21:22:13.455790: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/ohpc/pub/spack/opt/spack/linux-centos7-x86_64/gcc-8.3.0/python-3.7.4-3tniqr5iaaddvr3mbambcec3e5ta5qjp/lib:/opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/lib:/opt/ohpc/pub/compiler/gcc/8.3.0/lib64:/cm/local/apps/cuda-driver/libs/390.46/lib64
2020-01-21 21:22:13.455810: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2020-01-21 21:22:13.458392: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/ohpc/pub/spack/opt/spack/linux-centos7-x86_64/gcc-8.3.0/python-3.7.4-3tniqr5iaaddvr3mbambcec3e5ta5qjp/lib:/opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/lib:/opt/ohpc/pub/compiler/gcc/8.3.0/lib64:/cm/local/apps/cuda-driver/libs/390.46/lib64
2020-01-21 21:22:13.458411: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2020-01-21 21:22:27.404283: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/ohpc/pub/spack/opt/spack/linux-centos7-x86_64/gcc-8.3.0/python-3.7.4-3tniqr5iaaddvr3mbambcec3e5ta5qjp/lib:/opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/lib:/opt/ohpc/pub/compiler/gcc/8.3.0/lib64:/cm/local/apps/cuda-driver/libs/390.46/lib64
2020-01-21 21:22:27.404328: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: UNKNOWN ERROR (303)
2020-01-21 21:22:27.404357: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (node087.hpc.fau.edu): /proc/driver/nvidia/version does not exist
2020-01-21 21:22:27.404729: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-01-21 21:22:27.422668: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2594170000 Hz
2020-01-21 21:22:27.423919: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x6a74010 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-01-21 21:22:27.423953: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-01-21 21:22:28.232561: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/ohpc/pub/spack/opt/spack/linux-centos7-x86_64/gcc-8.3.0/python-3.7.4-3tniqr5iaaddvr3mbambcec3e5ta5qjp/lib:/opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/lib:/opt/ohpc/pub/compiler/gcc/8.3.0/lib64:/cm/local/apps/cuda-driver/libs/390.46/lib64
2020-01-21 21:22:28.232602: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: UNKNOWN ERROR (303)
2020-01-21 21:22:28.232629: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (node087.hpc.fau.edu): /proc/driver/nvidia/version does not exist
2020-01-21 21:22:28.232907: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-01-21 21:22:28.256529: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2594170000 Hz
2020-01-21 21:22:28.257140: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x73fc2e0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-01-21 21:22:28.257154: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-01-21 21:22:28.349760: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/ohpc/pub/spack/opt/spack/linux-centos7-x86_64/gcc-8.3.0/python-3.7.4-3tniqr5iaaddvr3mbambcec3e5ta5qjp/lib:/opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/lib:/opt/ohpc/pub/compiler/gcc/8.3.0/lib64:/cm/local/apps/cuda-driver/libs/390.46/lib64
2020-01-21 21:22:28.349800: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: UNKNOWN ERROR (303)
2020-01-21 21:22:28.349826: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (node087.hpc.fau.edu): /proc/driver/nvidia/version does not exist
2020-01-21 21:22:28.350099: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-01-21 21:22:28.380571: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2594170000 Hz
2020-01-21 21:22:28.381139: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x72b7fa0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-01-21 21:22:28.381154: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-01-21 21:22:29.751103: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/ohpc/pub/spack/opt/spack/linux-centos7-x86_64/gcc-8.3.0/python-3.7.4-3tniqr5iaaddvr3mbambcec3e5ta5qjp/lib:/opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/lib:/opt/ohpc/pub/compiler/gcc/8.3.0/lib64:/cm/local/apps/cuda-driver/libs/390.46/lib64
2020-01-21 21:22:29.751142: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: UNKNOWN ERROR (303)
2020-01-21 21:22:29.751171: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (node087.hpc.fau.edu): /proc/driver/nvidia/version does not exist
2020-01-21 21:22:29.751471: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-01-21 21:22:29.759346: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2594170000 Hz
2020-01-21 21:22:29.759499: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x8245a20 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-01-21 21:22:29.759513: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-01-21 21:22:31.154671: I tensorflow/core/profiler/lib/profiler_session.cc:225] Profiler session started.
2020-01-21 21:22:31.156521: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcupti.so.10.1'; dlerror: libcupti.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/ohpc/pub/spack/opt/spack/linux-centos7-x86_64/gcc-8.3.0/python-3.7.4-3tniqr5iaaddvr3mbambcec3e5ta5qjp/lib:/opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/lib:/opt/ohpc/pub/compiler/gcc/8.3.0/lib64:/cm/local/apps/cuda-driver/libs/390.46/lib64
2020-01-21 21:22:31.156557: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1307] function cupti_interface_->Subscribe( &subscriber_, (CUpti_CallbackFunc)ApiCallback, this)failed with error CUPTI could not be loaded or symbol could not be found.
2020-01-21 21:22:31.156569: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1346] function cupti_interface_->ActivityRegisterCallbacks( AllocCuptiActivityBuffer, FreeCuptiActivityBuffer)failed with error CUPTI could not be loaded or symbol could not be found.
2020-01-21 21:22:31.167771: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1329] function cupti_interface_->EnableCallback( 0 , subscriber_, CUPTI_CB_DOMAIN_DRIVER_API, cbid)failed with error CUPTI could not be loaded or symbol could not be found.
2020-01-21 21:22:31.167821: I tensorflow/core/profiler/internal/gpu/device_tracer.cc:88]  GpuTracer has collected 0 callback api events and 0 activity events.
2020-01-21 21:22:31.178034: I tensorflow/core/profiler/lib/profiler_session.cc:225] Profiler session started.
2020-01-21 21:22:31.178295: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcupti.so.10.1'; dlerror: libcupti.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/ohpc/pub/spack/opt/spack/linux-centos7-x86_64/gcc-8.3.0/python-3.7.4-3tniqr5iaaddvr3mbambcec3e5ta5qjp/lib:/opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/lib:/opt/ohpc/pub/compiler/gcc/8.3.0/lib64:/cm/local/apps/cuda-driver/libs/390.46/lib64
2020-01-21 21:22:31.178320: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1307] function cupti_interface_->Subscribe( &subscriber_, (CUpti_CallbackFunc)ApiCallback, this)failed with error CUPTI could not be loaded or symbol could not be found.
2020-01-21 21:22:31.178330: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1346] function cupti_interface_->ActivityRegisterCallbacks( AllocCuptiActivityBuffer, FreeCuptiActivityBuffer)failed with error CUPTI could not be loaded or symbol could not be found.
2020-01-21 21:22:31.192692: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1329] function cupti_interface_->EnableCallback( 0 , subscriber_, CUPTI_CB_DOMAIN_DRIVER_API, cbid)failed with error CUPTI could not be loaded or symbol could not be found.
2020-01-21 21:22:31.192732: I tensorflow/core/profiler/internal/gpu/device_tracer.cc:88]  GpuTracer has collected 0 callback api events and 0 activity events.
2020-01-21 21:22:31.871333: I tensorflow/core/profiler/lib/profiler_session.cc:225] Profiler session started.
2020-01-21 21:22:31.871622: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcupti.so.10.1'; dlerror: libcupti.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/ohpc/pub/spack/opt/spack/linux-centos7-x86_64/gcc-8.3.0/python-3.7.4-3tniqr5iaaddvr3mbambcec3e5ta5qjp/lib:/opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/lib:/opt/ohpc/pub/compiler/gcc/8.3.0/lib64:/cm/local/apps/cuda-driver/libs/390.46/lib64
2020-01-21 21:22:31.871649: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1307] function cupti_interface_->Subscribe( &subscriber_, (CUpti_CallbackFunc)ApiCallback, this)failed with error CUPTI could not be loaded or symbol could not be found.
2020-01-21 21:22:31.871660: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1346] function cupti_interface_->ActivityRegisterCallbacks( AllocCuptiActivityBuffer, FreeCuptiActivityBuffer)failed with error CUPTI could not be loaded or symbol could not be found.
2020-01-21 21:22:31.890759: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1329] function cupti_interface_->EnableCallback( 0 , subscriber_, CUPTI_CB_DOMAIN_DRIVER_API, cbid)failed with error CUPTI could not be loaded or symbol could not be found.
2020-01-21 21:22:31.890804: I tensorflow/core/profiler/internal/gpu/device_tracer.cc:88]  GpuTracer has collected 0 callback api events and 0 activity events.
2020-01-21 21:22:37.572670: I tensorflow/core/profiler/lib/profiler_session.cc:225] Profiler session started.
2020-01-21 21:22:37.579682: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcupti.so.10.1'; dlerror: libcupti.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/ohpc/pub/spack/opt/spack/linux-centos7-x86_64/gcc-8.3.0/python-3.7.4-3tniqr5iaaddvr3mbambcec3e5ta5qjp/lib:/opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/lib:/opt/ohpc/pub/compiler/gcc/8.3.0/lib64:/cm/local/apps/cuda-driver/libs/390.46/lib64
2020-01-21 21:22:37.579714: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1307] function cupti_interface_->Subscribe( &subscriber_, (CUpti_CallbackFunc)ApiCallback, this)failed with error CUPTI could not be loaded or symbol could not be found.
2020-01-21 21:22:37.579725: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1346] function cupti_interface_->ActivityRegisterCallbacks( AllocCuptiActivityBuffer, FreeCuptiActivityBuffer)failed with error CUPTI could not be loaded or symbol could not be found.
2020-01-21 21:22:37.595865: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1329] function cupti_interface_->EnableCallback( 0 , subscriber_, CUPTI_CB_DOMAIN_DRIVER_API, cbid)failed with error CUPTI could not be loaded or symbol could not be found.
2020-01-21 21:22:37.595895: I tensorflow/core/profiler/internal/gpu/device_tracer.cc:88]  GpuTracer has collected 0 callback api events and 0 activity events.
srun: error: node087: task 0: Segmentation fault
2020-01-22 00:03:33.844572: I tensorflow/core/profiler/lib/profiler_session.cc:225] Profiler session started.
2020-01-22 00:03:33.844656: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1307] function cupti_interface_->Subscribe( &subscriber_, (CUpti_CallbackFunc)ApiCallback, this)failed with error CUPTI could not be loaded or symbol could not be found.
2020-01-22 00:03:33.844667: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1346] function cupti_interface_->ActivityRegisterCallbacks( AllocCuptiActivityBuffer, FreeCuptiActivityBuffer)failed with error CUPTI could not be loaded or symbol could not be found.
2020-01-22 00:03:33.853920: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1329] function cupti_interface_->EnableCallback( 0 , subscriber_, CUPTI_CB_DOMAIN_DRIVER_API, cbid)failed with error CUPTI could not be loaded or symbol could not be found.
2020-01-22 00:03:33.853946: I tensorflow/core/profiler/internal/gpu/device_tracer.cc:88]  GpuTracer has collected 0 callback api events and 0 activity events.
Traceback (most recent call last):
  File "../../cross-validator.py", line 107, in <module>
    x_valid, y_valid = x.iloc[validate_index].values, y.iloc[validate_index].values
  File "/home/jjohn273/git/ECBDL14-Classification/env/lib64/python3.6/site-packages/pandas/core/indexing.py", line 1424, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/home/jjohn273/git/ECBDL14-Classification/env/lib64/python3.6/site-packages/pandas/core/indexing.py", line 2148, in _getitem_axis
    return self._get_list_axis(key, axis=axis)
  File "/home/jjohn273/git/ECBDL14-Classification/env/lib64/python3.6/site-packages/pandas/core/indexing.py", line 2130, in _get_list_axis
    return self.obj.take(key, axis=axis)
  File "/home/jjohn273/git/ECBDL14-Classification/env/lib64/python3.6/site-packages/pandas/core/generic.py", line 3604, in take
    indices, axis=self._get_block_manager_axis(axis), verify=True
  File "/home/jjohn273/git/ECBDL14-Classification/env/lib64/python3.6/site-packages/pandas/core/internals/managers.py", line 1397, in take
    new_axis=new_labels, indexer=indexer, axis=axis, allow_dups=True
  File "/home/jjohn273/git/ECBDL14-Classification/env/lib64/python3.6/site-packages/pandas/core/internals/managers.py", line 1267, in reindex_indexer
    for blk in self.blocks
  File "/home/jjohn273/git/ECBDL14-Classification/env/lib64/python3.6/site-packages/pandas/core/internals/managers.py", line 1267, in <listcomp>
    for blk in self.blocks
  File "/home/jjohn273/git/ECBDL14-Classification/env/lib64/python3.6/site-packages/pandas/core/internals/blocks.py", line 1313, in take_nd
    values, indexer, axis=axis, allow_fill=allow_fill, fill_value=fill_value
  File "/home/jjohn273/git/ECBDL14-Classification/env/lib64/python3.6/site-packages/pandas/core/algorithms.py", line 1716, in take_nd
    out = np.empty(out_shape, dtype=dtype)
MemoryError: Unable to allocate 1.39 GiB for an array with shape (933333, 200) and data type float64
srun: error: node087: task 0: Exited with exit code 1
2020-01-22 01:36:38.653302: I tensorflow/core/profiler/lib/profiler_session.cc:225] Profiler session started.
2020-01-22 01:36:38.653377: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1307] function cupti_interface_->Subscribe( &subscriber_, (CUpti_CallbackFunc)ApiCallback, this)failed with error CUPTI could not be loaded or symbol could not be found.
2020-01-22 01:36:38.653387: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1346] function cupti_interface_->ActivityRegisterCallbacks( AllocCuptiActivityBuffer, FreeCuptiActivityBuffer)failed with error CUPTI could not be loaded or symbol could not be found.
2020-01-22 01:36:38.662436: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1329] function cupti_interface_->EnableCallback( 0 , subscriber_, CUPTI_CB_DOMAIN_DRIVER_API, cbid)failed with error CUPTI could not be loaded or symbol could not be found.
2020-01-22 01:36:38.662470: I tensorflow/core/profiler/internal/gpu/device_tracer.cc:88]  GpuTracer has collected 0 callback api events and 0 activity events.
2020-01-22 02:30:25.676714: I tensorflow/core/profiler/lib/profiler_session.cc:225] Profiler session started.
2020-01-22 02:30:25.676781: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1307] function cupti_interface_->Subscribe( &subscriber_, (CUpti_CallbackFunc)ApiCallback, this)failed with error CUPTI could not be loaded or symbol could not be found.
2020-01-22 02:30:25.676793: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1346] function cupti_interface_->ActivityRegisterCallbacks( AllocCuptiActivityBuffer, FreeCuptiActivityBuffer)failed with error CUPTI could not be loaded or symbol could not be found.
2020-01-22 02:30:25.685780: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1329] function cupti_interface_->EnableCallback( 0 , subscriber_, CUPTI_CB_DOMAIN_DRIVER_API, cbid)failed with error CUPTI could not be loaded or symbol could not be found.
2020-01-22 02:30:25.685811: I tensorflow/core/profiler/internal/gpu/device_tracer.cc:88]  GpuTracer has collected 0 callback api events and 0 activity events.
2020-01-22 04:52:29.595971: I tensorflow/core/profiler/lib/profiler_session.cc:225] Profiler session started.
2020-01-22 04:52:29.596027: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1307] function cupti_interface_->Subscribe( &subscriber_, (CUpti_CallbackFunc)ApiCallback, this)failed with error CUPTI could not be loaded or symbol could not be found.
2020-01-22 04:52:29.596037: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1346] function cupti_interface_->ActivityRegisterCallbacks( AllocCuptiActivityBuffer, FreeCuptiActivityBuffer)failed with error CUPTI could not be loaded or symbol could not be found.
2020-01-22 04:52:29.610043: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1329] function cupti_interface_->EnableCallback( 0 , subscriber_, CUPTI_CB_DOMAIN_DRIVER_API, cbid)failed with error CUPTI could not be loaded or symbol could not be found.
2020-01-22 04:52:29.610085: I tensorflow/core/profiler/internal/gpu/device_tracer.cc:88]  GpuTracer has collected 0 callback api events and 0 activity events.
